name: NoAdvancementsInCreative
author: s0me0ne-coder
description: A really simple plugin to cancel events realted to advancement progress if gamemode is creative
website: https://github.com/s0me0ne-coder/NoAdvancementsInCreative
version: 1.0
api-version: 1.18
main: plugin.NoAdvancementsInCreative
